### ISSUE TITLE
Relicense as LGPL?

### ISSUE THREAD

**Issue by lostmsu** [Nexus-Mods/NexusMods.Paths#12]
See the issue in https://github.com/erri120/GameFinder/issues/75

My understanding is that this library being GPL makes it basically illegal to use GameFinder in practice.

Yes, dynamic linking in GPL is up for debate, but:
1. Switching to LGPL will alleviate the risk of the need to resolve this debate in courts.
2. AFAIK LGPL is almost exactly GPL + dynamic linking free reign, which matches the intent with no downsides.
3. It is easy to relicense with ~30 commits and 3 authors. Later it would take chasing every single commiter out, and either getting approval or reimplementing their contributions.

**Comment by Sewer56** [comment]
I'll let @halgari do the talking on this one; since ultimately they have the final say on this repo.
It's a pretty complicated situation, and has been brought up briefly before internally too; however not much really happened.

Note: There's 4 authors for this one; I actually wrote around 35% of this library's current code, but my name doesn't show here since the code originally lived in https://github.com/Nexus-Mods/NexusMods.App and I haven't worked on this library since.

**Comment by lostmsu** [comment]
@Sewer56 ultimately you'd need to explicitly approve this for your contributions.

**Comment by Sewer56** [comment]
To give my stance on it.
I have personally no objections towards re-licensing my parts as LGPLv3.

Though it could also be argued that the company owns the codebase, rather than us individual contributors, since we built this on company time; and thus, is not up to me to decide as the company entity would effectively be the author/owner.

(I'd have to check my contract to figure out, I don't remember)

----

Anyway to give some additional background.

With GPLv3, these things aren't very clear cut. For instance, when you consume `NexusMods.Paths` in a standard .NET application; you are effectively dynamically linking to it (as runtime loads the DLL and JIT processes the IL code when needed). 

For example, you can argue that dynamic linking can create derived works; but then we look in the real world, and see the likes of prioprietary (DKMS) kernel modules for Linux; which becomes unclear, as Linux is GPL licensed.

Over here in Europe at least dynamic linking of GPL hasn't been court-tested.

As I see it; the current state is problematic for use cases like NativeAOT in non-GPL projects where you are performing static linking but is more of a gray area for regular linking within the confines of regular .NET Runtime.

**Comment by halgari** [comment]
I'm reluctant to switch our code to LGPL vs GPL because LGPL allows for commerical use of the software if it is dynamically linked. Use of this software in commerical software is something I'm actively against as we intend for the whole project to remain open and free. 

It seems though the problem is then with the license of GameFinder or GameFinder's usage of this library. I think I'd rather it be removed from GameFinder or GameFinder be relicensed. Commerical use of modding tools is a hotly debated topic, and I'm using the license of our codebase to setup a clear standard that modding software should be free, and remian free.

**Comment by lostmsu** [comment]
@halgari the request is not for the whole software but for this lib only due to the above issue with GameFinder

**Comment by halgari** [comment]
I understand this, but my same reasoning applies

**Comment by erri120** [comment]
GameFinder 4.0.0 and later releases will be published under GPLv3. See https://github.com/erri120/GameFinder/commit/53130f2d39fcb061366f4da9fcc695b8e0d8dd61 for details.
